import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "@/components/custom/header-nav";
import FooterPromotion from "@/components/custom/footer-promotion";
import Footer from "@/components/custom/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="relative">
                    <HeaderNav />
                    {children}
                    <FooterPromotion />
                    <Footer />
                </div>
            </body>
        </html>
    );
}
